# Generated by Django 5.1.7 on 2025-03-12 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('release_date', models.DateField(null=True)),
                ('runtime', models.PositiveIntegerField(null=True)),
                ('budget', models.BigIntegerField(null=True)),
                ('revenue', models.BigIntegerField(null=True)),
                ('genres', models.JSONField(default=list)),
                ('production_countries', models.JSONField(default=list)),
                ('spoken_languages', models.JSONField(default=list)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
