# Generated by Django 4.2.20 on 2025-03-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.movie'),
        ),
    ]
