# Generated by Django 4.2.20 on 2025-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_userfavorite_movie_alter_userfavorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
