# Generated by Django 4.2.20 on 2025-05-28 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0010_cinema_movieschedule_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movieschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='movieschedule',
            name='hall_name',
        ),
        migrations.RemoveField(
            model_name='movieschedule',
            name='seats_layout',
        ),
        migrations.RemoveField(
            model_name='movieschedule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(default='未知城市', max_length=100),
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='address',
            field=models.TextField(default='地址待更新'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(default='未知影院', max_length=255),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='movies.cinema'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='movies.movieschedule'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['city'], name='movies_cine_city_021846_idx'),
        ),
        migrations.AddIndex(
            model_name='cinema',
            index=models.Index(fields=['latitude', 'longitude'], name='movies_cine_latitud_7e0c28_idx'),
        ),
        migrations.AddIndex(
            model_name='movieschedule',
            index=models.Index(fields=['movie', 'cinema'], name='movies_movi_movie_i_5110e8_idx'),
        ),
        migrations.AddIndex(
            model_name='movieschedule',
            index=models.Index(fields=['start_time'], name='movies_movi_start_t_67a201_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='movies_orde_user_id_d708a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='movies_orde_order_n_619c72_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='movies_orde_status_4e7cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='movies_orde_created_8a0649_idx'),
        ),
        migrations.AddConstraint(
            model_name='movieschedule',
            constraint=models.UniqueConstraint(fields=('movie', 'cinema', 'start_time'), name='unique_movie_cinema_schedule'),
        ),
    ]
