# Generated by Django 4.2.20 on 2025-05-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_cinema_options_alter_movieschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='movies.movieschedule'),
        ),
    ]
