# Generated by Django 4.2.20 on 2025-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_user', 'Can manage users'), ('manage_content', 'Can manage content'), ('view_analytics', 'Can view analytics')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='登录次数'),
        ),
    ]
