# Generated by Django 4.2.20 on 2025-05-22 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_reply_replyimage_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.reply', verbose_name='父回复'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='可选字段，系统会自动生成唯一用户名', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='users_custo_usernam_a8ad03_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='users_post_user_id_94c3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='users_post_status_bef5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['post', 'created_at'], name='users_reply_post_id_e81f47_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['parent'], name='users_reply_parent__2491f7_idx'),
        ),
    ]
