# Generated by Django 4.2.20 on 2025-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_postimage_options_remove_reply_parent_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
