# Generated by Django 4.2.20 on 2025-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pointlog_postfavorite_postlike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='users_post_status_bef5b9_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'is_pinned'], name='users_post_status_70350a_idx'),
        ),
    ]
