# Generated by Django 4.2.20 on 2025-05-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_post_options_and_more'),
    ]

    operations = [
        # 先删除外键约束
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 0;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 1;"
        ),
        
        # 删除重复的电影相关表
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_orderchange_new_seats;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_orderchange_old_seats;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_orderchange;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_movieorder_seats;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_movieorder;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_seat;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS users_moviesession;",
            reverse_sql="-- 无法恢复已删除的表"
        ),
        
        # 重新启用外键检查
        migrations.RunSQL(
            "SET FOREIGN_KEY_CHECKS = 1;",
            reverse_sql="SET FOREIGN_KEY_CHECKS = 0;"
        ),
    ]
