# Generated by Django 4.2.20 on 2025-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250528_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
