# Generated by Cursor on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(
                choices=[
                    ('user', '普通用户'),
                    ('movie_admin', '电影管理员'),
                    ('forum_admin', '论坛管理员'),
                    ('order_admin', '订单管理员'),
                ],
                default='user',
                max_length=20,
                verbose_name='管理员角色',
            ),
        ),
    ]

